name: ARMP_env
channels:
  - conda-forge
dependencies:
  # ==================
  # Base
  # ==================
  - python=3.10
  - numpy
  - pandas
  - xarray
  - xcdat
  - eofs
  - matplotlib
  - dataclasses
  - regionmask
  # ==================
  # Testing
  # ==================
  - pre_commit